/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package students;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStream;
import java.io.FileInputStream;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.*;
import student_management.DbConnect;
import com.google.gson.Gson;
import net.glxn.qrgen.core.image.ImageType;
import net.glxn.qrgen.javase.QRCode;
/**
 *
 * @author suhana choudhary
 */
public class AddStudents extends javax.swing.JFrame {
    String imgPath;
    ByteArrayOutputStream out =null;
    ImageIcon icon;
    byte[] imageData;
    /**
     * Creates new form AddStudents
     */
    public AddStudents() {
        initComponents();
        
        try{
            Connection con=DbConnect.connect();
            PreparedStatement ps=con.prepareStatement("select max(rollno) from studData");
            ResultSet rs=ps.executeQuery();
            
            if(rs.next()){
                String it=rs.getString(1).substring(0,7);
                int rollno=Integer.parseInt(rs.getString(1).substring(7))+1;
                t2.setText(it+rollno);
                t2.setEditable(false);
            }
            
            else{
                System.out.println("error");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    public ImageIcon resizePic(String pic) {
        ImageIcon myimg = new ImageIcon(pic);
        Image img = myimg.getImage().getScaledInstance(myImage.getWidth(), myImage.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }
    
    public void generateQR(){
        Map<String,String>data=new HashMap<>();
        data.put("name",t1.getText());
        data.put("email", t3.getText());
        data.put("rollno", t2.getText());
        
        Gson gson=new Gson();
        String jsonData=gson.toJson(data);
        out=QRCode.from(jsonData).withSize(300,250).to(ImageType.PNG).stream();
        
        try{
            imageData=out.toByteArray();
            icon=new ImageIcon(imageData);
        }catch(Exception e){
            System.out.println(e);
        }
    }
//    
//    private void choiceActionPerformed(java.awt.event.ActionEvent evt) {                                       
//        
//        
//    }                                      


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        choice = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        c1 = new javax.swing.JComboBox<>();
        t8 = new com.toedter.calendar.JDateChooser();
        myImage = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Upload an Image");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 190, 50));

        choice.setBackground(new java.awt.Color(255, 102, 0));
        choice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        choice.setForeground(new java.awt.Color(255, 255, 255));
        choice.setText("Upload");
        choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceActionPerformed(evt);
            }
        });
        jPanel1.add(choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 347, 160, 52));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 120, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Roll Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 116, 120, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 176, 100, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Class XII (%)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 120, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Course");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 300, 110, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adhaar No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 356, 109, 47));

        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 210, 40));

        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 210, 40));

        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 210, 40));

        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 210, 40));

        t5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel1.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 354, 585, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 409, 110, 72));

        t6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel1.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 580, 100));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Father's name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 150, 50));

        t7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel1.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 200, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date of Birth");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 110, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Phone");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 176, 90, 40));

        t9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel1.add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 200, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Class XI (%)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 110, 50));

        t10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel1.add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 200, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Branch");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 298, 75, 50));

        c2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "computer science", "electronics", "electrical", "mechanical", "civil" }));
        c2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 297, 200, 41));

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.tech", "BCA", "B.SC", "MBA", "BBA", "MCA", " " }));
        c1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 210, 40));

        t8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 2));
        jPanel1.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 116, 198, 36));

        myImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 2));
        jPanel1.add(myImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 220, 230));

        submit.setBackground(new java.awt.Color(255, 51, 0));
        submit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Add");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 553, 120, 40));

        cancel.setBackground(new java.awt.Color(255, 51, 0));
        cancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 553, 120, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background2 (1).jpg"))); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 5), "Add Student", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Semibold", 0, 24), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try{
            Connection con=DbConnect.connect();
            PreparedStatement a1=con.prepareStatement("insert into attendence values(?,'-','-')");
            a1.setString(1,t2.getText());
            a1.executeUpdate();
            
            
                InputStream ig=new FileInputStream(new File(imgPath));
                generateQR();
                InputStream qr=new ByteArrayInputStream(imageData);

                PreparedStatement ps = con.prepareStatement("insert into studdata values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1,t1.getText()); // name
                ps.setString(2,t2.getText()); // roll no
                ps.setString(3,t3.getText()); // email id
                ps.setString(4,t4.getText()); // class xii
                ps.setString(5,c1.getSelectedItem().toString()); // course
                ps.setString(6,t5.getText()); // aadhar
                ps.setString(7,t6.getText()); // address
                ps.setString(8,t7.getText()); // father
                ps.setString(9,((JTextField)t8.getDateEditor().getUiComponent()).getText()); // dob
                ps.setString(10,t9.getText()); // phone
                ps.setString(11,t10.getText()); // x class
                ps.setString(12,c2.getSelectedItem().toString()); // branch
                ps.setBlob(13,ig); // image 
                ps.setBlob(14,qr); // qr code 

                int a = ps.executeUpdate();
                if(a==1){
                    JOptionPane.showMessageDialog(null,"Successfully registered a new Student");
                    dispose();
                }
                else
                   JOptionPane.showMessageDialog(null,"Some Error");

            }
        catch(Exception e){
                System.out.println(e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void choiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter(".Images", "jpg", "png", "jpeg", "gif");

        file.addChoosableFileFilter(filefilter);
        int filestate = file.showSaveDialog(null);

        if (filestate == JFileChooser.APPROVE_OPTION) {
            File sf = file.getSelectedFile();
            String path = sf.getAbsolutePath();

            myImage.setIcon(resizePic(path));
            imgPath = path;
        }
        else if (filestate == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showConfirmDialog(null, "NO IMAGE SELECTED");
        }
    }//GEN-LAST:event_choiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton cancel;
    private javax.swing.JButton choice;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel myImage;
    private javax.swing.JButton submit;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private com.toedter.calendar.JDateChooser t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
